version: "3.3"

services:

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - ./api:/api/src/app
      - /api/src/app/node_modules
    command: npm run start:dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:user@postgres:5432/database
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - ./frontend:/frontend/src/app
      - /frontend/src/app/node_modules
    environment:
      PORT: 4200
    ports:
      - 4200:4200
    links:
      - api

  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: database
    ports:
      - 35000:5432

  postgres_admin:
    image: dpage/pgadmin4:7.5
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
